name: ssu_find
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.3
  image_picker: ^1.0.7 # updated
  # For web support (optional, helpful for debugging web issues)
  http: ^0.13.6
  intl: ^0.18.1  # For date formatting
  crypto: ^3.0.3
  firebase_auth_web: any
  cloud_firestore_web: any
  firebase_storage_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
